### ISSUE TITLE
500 INTERNAL ERROR with plugin redmine_tags

### ISSUE THREAD

**Issue by ashrafalzyoud** [redmica/redmine_issues_panel#47]
issues_panel/issue_query_patch.rb:14:in `build_from_params'
plugins/redmineup_tags/lib/redmineup_tags/patches/issue_query_patch.rb:64:in `build_from_params_with_redmine_tags'
plugins/redmine_issues_panel/lib/redmine_issues_panel/issue_query_patch.rb:14:in `build_from_params'
plugins/redmineup_tags/lib/redmineup_tags/patches/issue_query_patch.rb:64:in `build_from_params_with_redmine_tags'
plugins/redmine_issues_panel/lib/redmine_issues_panel/issue_query_patch.rb:14:in `build_from_params'
plugins/redmineup_tags/lib/redmineup_tags/patches/issue_query_patch.rb:64:in `build_from_params_with_redmine_tags'
plugins/redmine_issues_panel/lib/redmine_issues_panel/issue_query_patch.rb:14:in `build_from_params'

**Comment by ashrafalzyoud** [comment]
if im change line 13
`      def build_from_params_without_redmine_tags(params, defaults={})`
its working
are this solution ok or no??

**Comment by ashrafalzyoud** [comment]
@takenory 
@salmanmp

**Comment by salmanmp** [comment]
There is two way to patch a class existing function. Using alias_method and prepend module. If you do patch on same function in both ways, you will fall in loop and get such error mentioned in first message.

**Comment by ashrafalzyoud** [comment]
@salmanmp 
ok then how i can fix it

**Comment by salmanmp** [comment]
> @salmanmp ok then how i can fix it

As I mentioned, you must make all of pathces on one function, the same way.

**Comment by ashrafalzyoud** [comment]
i dont know how
if u can help plz?
